default_platform(:android)

platform :android do
  private_lane :setup_variables do
    PACKAGE_NAME = ENV["PACKAGE_NAME"]
    BUILD_NUMBER_PATH = ENV["BUILD_NUMBER_PATH"]
  end

  before_all do
    setup_variables
  end

  lane :release do |options|
    build_apk
  end

  lane :build do |options|
    update_build_number
    build_apk
  end

  # Private Lanes
  desc "Download dependencies"
  private_lane :download_dependencies do
    gradle(task: "androidDependencies")
  end

  private_lane :fetch_build_number do
    sh(
      command: "cat #{BUILD_NUMBER_PATH}"
    )

  end

  private_lane :update_build_number do
    buildNumber = fetch_build_number.to_i + 1
    value = sh(command: "echo #{buildNumber} > #{BUILD_NUMBER_PATH}")
  end

  lane :generate_changelog_text do
    "#{git_branch}\n#{changelog_from_git_commits( commits_count: "10")}"
  end
end
