default_platform(:android)

platform :android do
  private_lane :setup_variables do
    PACKAGE_NAME = ENV["PACKAGE_NAME"]
  end

  before_all do
    setup_variables
  end

  lane :release do |options|
    build_apk
  end

  lane :build do |options|
    update_build_number
    build_apk
  end

  # Private Lanes
  desc "Download dependencies"
  private_lane :download_dependencies do
    gradle(task: "androidDependencies")
  end

  lane :generate_changelog_text do
    "#{git_branch}\n#{changelog_from_git_commits( commits_count: "10")}"
  end
end
